### ISSUE TITLE
News component - various header image heights

### ISSUE THREAD

**Issue by Doodlepaul** [wmcadigital/wmca-design-system#152] opened 2021-05-06 13:43 UTC
**Describe the bug**
The header image is different heights on when the component spans two columns in comparison to the one. 

**To Reproduce**
1. Go to https://deploy-preview-148--wmcads.netlify.app/templates/homepage/

**Expected behavior**
All header image heights should be consistent to allow alignment across the row.

**Screenshots**
![Screenshot 2021-05-06 at 14 38 02](https://user-images.githubusercontent.com/68856858/117307695-b0c5e580-ae78-11eb-9f1b-e18fd25426d2.png)

**Desktop (please complete the following information):**
OS: macOS
Browser: Safari
Version: 14.1

**Comment by rolorogan** [comment] 2021-05-06 14:41
Closing as duplicate of Issue #114

**Closed** 2021-05-06 14:41 UTC
