### ISSUE TITLE
Favicon needs to change on the design system

### ISSUE THREAD

**Issue by Doodlepaul** [wmcadigital/wmca-design-system#161] opened 2021-05-06 14:44 UTC
**Describe the bug**
Favicon is currently TfWM

**To Reproduce**
1. Go to https://deploy-preview-148--wmcads.netlify.app/templates/campaign-two-columns/

**Expected behavior**
Would expect it to be WMCA hexagon - similar to beta.

**Screenshots**
![Screenshot 2021-05-06 at 15 42 43](https://user-images.githubusercontent.com/68856858/117317944-e3281080-ae81-11eb-9d87-f7d22784a7d1.png)

**Desktop (please complete the following information):**
OS: macOS
Browser: Safari
Version: 14.1

**Comment by rolorogan** [comment] 2021-05-06 14:49
Duplicate of #158

**Closed** 2021-05-06 14:49 UTC
Labels: duplicate
